# FOR UNO
BOARD := arduino:avr:uno
PORT := /dev/ttyUSB0

# FOR TINY
#BOARD := attiny:avr:ATtinyX5:cpu=attiny85,clock=internal8
#PORT := /dev/ttyUSB0

#BOARD := arduino:avr:nano:cpu=atmega328isp

ARDDUDE_OPTIONS := -l cr -o raw -d
PORT := /dev/ttyUSB0
LIBRARY_PATH := ..
ARDUINO_CLI_UPLOAD_OPTS=-v
ARDUINO_CLI_COMPILE_OPTS=--build-property "build.extra_flags=-DREDUCED_MAP -DTHIN_FONT"
MAIN_SOURCE := example/example.ino